// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using odatawebapi.Entidades;

namespace webapi_odata_ef.Migrations
{
    [DbContext(typeof(PersonasDbContext))]
    partial class PersonasDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("odatawebapi.Entidades.Direccion", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("DireccionDesc")
                        .IsRequired()
                        .HasColumnType("nvarchar(150)")
                        .HasMaxLength(150);

                    b.Property<int?>("IdPersona")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("IdPersona");

                    b.ToTable("Direcciones");
                });

            modelBuilder.Entity("odatawebapi.Entidades.Persona", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("Edad")
                        .HasColumnType("int");

                    b.Property<string>("NombreYApellido")
                        .IsRequired()
                        .HasColumnType("nvarchar(50)")
                        .HasMaxLength(50);

                    b.HasKey("Id");

                    b.ToTable("Personas");
                });

            modelBuilder.Entity("odatawebapi.Entidades.Telefono", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int?>("IdPersona")
                        .HasColumnType("int");

                    b.Property<string>("TelefonoDesc")
                        .IsRequired()
                        .HasColumnType("nvarchar(150)")
                        .HasMaxLength(150);

                    b.HasKey("Id");

                    b.HasIndex("IdPersona");

                    b.ToTable("Telefonos");
                });

            modelBuilder.Entity("odatawebapi.Entidades.Direccion", b =>
                {
                    b.HasOne("odatawebapi.Entidades.Persona", "IdPersonaNavigation")
                        .WithMany("Direccion")
                        .HasForeignKey("IdPersona")
                        .HasConstraintName("FK_Direccion_IdPersona");
                });

            modelBuilder.Entity("odatawebapi.Entidades.Telefono", b =>
                {
                    b.HasOne("odatawebapi.Entidades.Persona", "IdPersonaNavigation")
                        .WithMany("Telefono")
                        .HasForeignKey("IdPersona")
                        .HasConstraintName("FK_Telefono_IdPersona");
                });
#pragma warning restore 612, 618
        }
    }
}
